WebApplication1/Models/CompanySummary.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Models
{
    public class CompanySummary
    {
        public int EmployeeCount { get; set; }

        public int AverageDepartmentEmployeeCount { get; set; }
    }
}

WebApplication1/Models/Department.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplication1.Models
{
    public class Department
    {
        public int Id { get; set; }
        
        [Display(Name="部门名称")]
        public string Name { get; set; }

        [Display(Name = "部门地址")]
        public string Location { get; set; }

        [Display(Name = "部门人数")]
        public int EmployeeCount { get; set; }
    }
}

WebApplication1/Models/Employee.cs
namespace WebApplication1.Models
{
    public class Employee
    {
        public int Id { get; set; }

        public int DepartmentId { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public Gender Gender { get; set; }

        public bool Fired { get; set; }
    }

    public enum Gender
    {
        女 = 0,
        男 = 1
    }
}

WebApplication1/Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using WebApplication1.Models;
using WebApplication1.Services;

namespace WebApplication1.Controllers
{
    public class DepartmentController : Controller
    {
        private readonly IDepartmentService _departmentService;
        private readonly IOptions<WebApplication1Options> _options;

        public DepartmentController(IDepartmentService departmentService,IOptions<WebApplication1Options> options)
        {
            _departmentService = departmentService;
            _options = options;
        }

        public async Task<IActionResult> Index()
        {
            ViewBag.Title = "Department Index";
            var department = await _departmentService.GetAll();
            return View(department);
        }

        public IActionResult Add()
        {
            ViewBag.Title = "Add Department";
            return View(new Department());
        }

        [HttpPost]
        public async Task<IActionResult> Add(Department department)
        {
            if (ModelState.IsValid)
            {
                await _departmentService.Add(department);
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

WebApplication1/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models;
using WebApplication1.Services;

namespace WebApplication1.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IDepartmentService _departmentService;
        private readonly IEmployeeService _employeeService;

        public EmployeeController(IDepartmentService departmentService, IEmployeeService employeeService)
        {
            _departmentService = departmentService;
            _employeeService = employeeService;
        }
        public async Task<IActionResult> Index(int departmentId)
        {
            var department = await _departmentService.GetById(departmentId);
            ViewBag.Title = $"Employees of {department.Name}";
            ViewBag.DepartmentId = departmentId;

            var employees = await _employeeService.GetByDepartmentId(departmentId);
            return View(employees);
        }

        public IActionResult Add(int departmentId)
        {
            ViewBag.Title = "Add Employee";
            return View(new Employee
            {
                DepartmentId = departmentId
            });
        }

        [HttpPost]
        public async Task<IActionResult> Add(Employee employee)
        {
            if (ModelState.IsValid)
            {
                await _employeeService.Add(employee);
            }
            return RedirectToAction(nameof(Index), new { departmentId = employee.DepartmentId });
        }


        public async Task<IActionResult> Fire(int employeeId)
        {
            var employee = await _employeeService.Fire(employeeId);
            return RedirectToAction(nameof(Index), new { departmentId = employee.DepartmentId });
        }
    }
}

WebApplication1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Services;

namespace WebApplication1.Controllers
{
    public class HomeController: Controller
    {
        public HomeController(IClock clock)
        {

        }
    }
}

WebApplication1/ViewComponents/CompanySummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication1.Services;

namespace WebApplication1.ViewComponents
{
    public class CompanySummaryViewComponent:ViewComponent
    {
        private readonly IDepartmentService _departmentService;

        public CompanySummaryViewComponent(IDepartmentService departmentService)
        {
            _departmentService = departmentService;
        }

        /// <summary>
        /// 该方法对应的视图为Views下的Shared下的Components下的CompanySummary下的Default.cshtml
        /// </summary>
        /// <param name="title"></param>
        /// <returns></returns>
        public async Task<IViewComponentResult> InvokeAsync(string title)
        {
            ViewBag.Title = title;
            var summary = await _departmentService.GetCompanySummary();
            return View(summary);
        }
    }
}

WebApplication1/Views/Department/Add.cshtml
@model WebApplication1.Models.Department


<form asp-action="Add">
    <div class="row form-group">
        <div class="col-md-2 offset-md-2">
            <label asp-for="Name" class="control-label"></label>
        </div>
        <div class="col-md-6">
            <input asp-for="Name" class="form-control" />
        </div>
    </div>
    <div class="row form-group">
        <div class="col-md-2 offset-md-2">
            <label asp-for="Location" class="control-label"></label>
        </div>
        <div class="col-md-6">
            <input asp-for="Location" class="form-control" />
        </div>
    </div>
    <div class="row form-group">
        <div class="col-md-2 offset-md-2">
            <label asp-for="EmployeeCount" class="control-label"></label>
        </div>
        <div class="col-md-6">
            <input asp-for="EmployeeCount" class="form-control" />
        </div>
    </div>
    <div class="row">
        <div class="col-md-2 offset-md-2">
            <input type="submit" value="Create" class="btn btn-primary" />
        </div>
    </div>
</form>

WebApplication1/Views/Department/DisplayTemplates/Department.cshtml
@using WebApplication1
@using WebApplication1.Models
@using Microsoft.Extensions.Options

@model Department
@inject IOptions<WebApplication1Options> options
<tr>
    @*如果人数大约配置中设置的人数，部门名称加粗*@
    @if (Model.EmployeeCount > options.Value.BoldDepartmentEmployeeCountThreshold)
    {
        <td><strong>@Model.Name</strong></td>
    }
    else
    {
        <td>@Model.Name</td>
    }

    <td>@Model.Location</td>
    <td>@Model.EmployeeCount</td>
    <td>
        @*asp-route-departmentId是asp-route-[参数名]；为Index页面传递参数*@
        <a asp-action="Index" asp-controller="Employee" asp-route-departmentId="@Model.Id">
            Employess
        </a>
    </td>
</tr>

WebApplication1/Views/Department/Index.cshtml
@using WebApplication1.Models
@model IEnumerable<Department>
<div class="row">
    <div class="col-md-10 offset-md-2">
        <table class="table">
            <tr>
                <th>Name</th>
                <th>Location</th>
                <th>Employee Count</th>
                <th>操作</th>
            </tr>
            @Html.DisplayForModel()
        </table>
    </div>
</div>
<div class="row">
    <div class="col-md-2">
        @await Component.InvokeAsync("CompanySummary", new { title = "部门列表页汇总1" })
        <br />
        <vc:company-summary title="部门列表页汇总2"></vc:company-summary>
    </div>
    <div class="col-md-4 offset-md-2">
        <a asp-action="Add">Add</a>
    </div>
</div>

WebApplication1/Views/Employee/Add.cshtml
@using WebApplication1.Models
@model Employee


<form asp-action="Add">
    <input type="hidden" asp-for="DepartmentId" />
    <div class="row form-group">
        <div class="col-md-2 offset-md-2">
            <label asp-for="FirstName" class="control-label"></label>
        </div>
        <div class="col-md-6">
            <input asp-for="FirstName" class="form-control" />
        </div>
    </div>
    <div class="row form-group">
        <div class="col-md-2 offset-md-2">
            <label asp-for="LastName" class="control-label"></label>
        </div>
        <div class="col-md-6">
            <input asp-for="LastName" class="form-control" />
        </div>
    </div>
    <div class="row form-group">
        <div class="col-md-2 offset-md-2">
            <label asp-for="Gender" class="control-label"></label>
        </div>
        <div class="col-md-6">
            @*下拉框，使用GetEnumSelectList获取枚举的元素*@
            <select class="form-control" asp-for="Gender" asp-items="Html.GetEnumSelectList<Gender>()"></select>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2 offset-md-2">
            <input type="submit" value="Create" class="btn btn-primary" />
        </div>
    </div>
</form>

WebApplication1/Views/Employee/DisplayTemplates/Employee.cshtml
@model WebApplication1.Models.Employee

    <tr>
        <td>@Model.FirstName</td>
        <td>@Model.LastName</td>
        <td>@Model.Gender</td>
        <td>@(Model.Fired?"是":"")</td>
        <td>
            @if (!Model.Fired)
            {
            <a asp-action="Fire" asp-route-employeeId="@Model.Id">
                Fire
            </a>
            }

        </td>
    </tr>

WebApplication1/Views/Employee/Index.cshtml
@using WebApplication1.Models
@model IEnumerable<Employee>
<div class="row">
    <div class="col-md-10 offset-md-2">
        <table class="table">
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Gender</th>
                <th>Is Fired</th>
                <th>操作</th>
            </tr>
            @Html.DisplayForModel()
        </table>
    </div>
</div>
<div class="row">
    <div class="col-md-4 offset-md-2">
        <a asp-action="Add" asp-route-departmentId="@ViewBag.DepartmentId">Add</a>
    </div>
</div>

WebApplication1/Views/Shared/Components/CompanySummary/Default.cshtml
@model WebApplication1.Models.CompanySummary
<div class="small">
    <div class="row h5">@ViewBag.Title</div>
    <div class="row">
        <div class="col-md-8">部门员工总数：</div>
        <div class="col-md-4">@Model.EmployeeCount</div>
    </div>
    <div class="row">
        <div class="col-md-8">部门平均人数：</div>
        <div class="col-md-4">@Model.AverageDepartmentEmployeeCount</div>
    </div>
</div>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @*开发环境*@
    <environment include="Development">
        @*导入不是压缩的文件*@
        <link rel="stylesheet" asp-href-include="css/*" asp-href-exclude="css/all.min.css" />
    </environment>

    @*不是开发环境*@
    <environment exclude="Development">
        <link rel="stylesheet" asp-href-include="css/all.min.css" />
    </environment>
</head>
<body>
    <img src="~/images/datebox_arrow.png" asp-append-version="true" />
    <h3>@ViewBag.Title</h3>
    <div>
        @RenderBody()
    </div>
</body>
</html>